CREATE TABLE solarnode.ocpp_authorization (
	id					BIGINT NOT NULL GENERATED BY DEFAULT AS IDENTITY,
	token				VARCHAR(20) NOT NULL,
	created				TIMESTAMP NOT NULL DEFAULT CURRENT_TIMESTAMP,
	enabled				BOOLEAN NOT NULL DEFAULT true,
	expires				TIMESTAMP,
	parent_id			VARCHAR(20),
	CONSTRAINT ocpp_authorization_pk PRIMARY KEY (id),
	CONSTRAINT ocpp_ocpp_authorization_unq UNIQUE (token)
);

INSERT INTO solarnode.sn_settings (skey, svalue) 
VALUES ('solarnode.ocpp_authorization.version', '1');
