CREATE TABLE solarnode.ocpp_system_user (
	id					BIGINT NOT NULL GENERATED BY DEFAULT AS IDENTITY,
	created				TIMESTAMP NOT NULL WITH DEFAULT CURRENT_TIMESTAMP,
	username			VARCHAR(64),
	password			VARCHAR(64),
	CONSTRAINT ocpp_system_user_pk PRIMARY KEY (id),
	CONSTRAINT ocpp_system_user_unq UNIQUE (username)
);

CREATE TABLE solarnode.ocpp_system_user_cp (
	user_id				BIGINT NOT NULL,
	idx					INTEGER NOT NULL,
	cp_id				VARCHAR(255) NOT NULL,
	CONSTRAINT ocpp_system_user_cp_pk PRIMARY KEY (user_id, idx),
	CONSTRAINT ocpp_system_user_cp_system_user_fk FOREIGN KEY (user_id)
		REFERENCES solarnode.ocpp_system_user (id)
		ON DELETE CASCADE
);

INSERT INTO solarnode.sn_settings (skey, svalue) 
VALUES ('solarnode.ocpp_system_user.version', '1');
